name: form_app
description: A sample demonstrating different types of forms and best practices
publish_to: "none"
version: 1.0.0+1

scripts:
  start:
    android: "cd android && ./gradlew app:assembleDebug -Ptarget=`pwd`/../integration_test/appium.dart && adb uninstall dev.flutter.formApp.form_app && adb install -r `pwd`/../build/app/outputs/apk/debug/app-debug.apk"
    simulator: "flutter build ios integration_test/appium.dart  --simulator && xcrun simctl install booted ./build/ios/iphonesimulator/Runner.app && xcrun simctl spawn booted log stream | grep flutter"

environment:
  sdk: ^3.4.0-0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  http: ^1.0.0
  json_annotation: any
  english_words: ^4.0.0
  cupertino_icons: ^1.0.2
  meta: ^1.3.0
  provider: ^6.0.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  go_router: ^14.0.0
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  build_runner: ^2.1.8
  appium_flutter_server:
    path: ../server

flutter:
  uses-material-design: true
