#for json_serializer
targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            "^lib/src/models/api/{{}}.dart": "lib/src/models/api/generated/{{}}.g.dart"
