on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*' # tag pattern on pub.dev: 'v{{version}'

name: Publish to pub.dev
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    defaults:
      run:
        working-directory: server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          working-directory: server
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2
      - name: Install dependencies
        run: flutter pub get
      - name: Publish
        run: dart pub publish --force

      - name: Update Flutter Driver with Version
        run: |
         TAG_NAME=$(curl -s "https://api.github.com/repos/AppiumTestDistribution/appium-flutter-server/tags" | grep -m 1 '"name"' | sed -E 's/.*"name": "([^"]+)".*/\1/') 
         repo_owner="AppiumTestDistribution" 
         repo_name="appium-flutter-integration-driver"  
         event_type="server-update" 
         service="Server to Driver"
         version=$TAG_NAME
          
         curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"
