on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*' # tag pattern on pub.dev: 'v{{version}'

name: Publish to pub.dev
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    defaults:
      run:
        working-directory: server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          working-directory: server
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
      - name: Install dependencies
        run: flutter pub get
      - name: Publish
        run: dart pub publish --force
